### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by gzambran** [google/transitfeed#434]
Collecting transitfeed
  Downloading transitfeed-1.2.14.tar.gz (347kB)
    100% |████████████████████████████████| 348kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-_nenm9v_/transitfeed/setup.py", line 34
        except ImportError, e:
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-_nenm9v_/transitfeed/

**Comment by MuckT** [comment]
I was able to install correctly on a fresh Linux machine using "sudo pip
install transitfeed". I've seen similar errors before especially if there
are multiple installs of Python on a computer: a common problem for those
using ESRI. Check with "pip list" that the module isn't installed somewhere
else.

Some Similar Problems:
https://stackoverflow.com/questions/17886647/cant-install-via-pip-because-of-egg-info-error

https://github.com/donnemartin/gitsome/issues/4

**Comment by gzambran** [comment]
I definitely have 2 installs of Python on my computer but that hasn't caused issues with any other installs. I even aliased python to python3.6 but still have the same issue.

**Comment by gzambran** [comment]
I see my silly mistake. Didn't realize this isn't supported for Python 3

**Comment by avilaton** [comment]
Issue is caused by incompatibility with python 3, tracked in #412 . This can be marked as duplicate and closed.
